#!/bin/sh

# Setup =======================================================================

TERM_SIZE=$(stty size)
TERM_HEIGHT=${TERM_SIZE% *}
TERM_WIDTH=${TERM_SIZE#* }

PROMPT_HEIGHT=3 #TODO

# Info ------------------------------------------------------------------------

#TODO

COLOR=4
USERNAME=${USER}
HOSTNAME=$(hostname)
OS=$(lsb_release -sd | sed -e 's/"//g')
KERNEL=$(uname -sr)
UPTIME=$(uptime -p | sed -e 's/up //')
SHELL=$(basename "${SHELL}")
WM='<your_wm>'
TERMINAL='<your_terminal>'

INFO=$(gum style "[1;38;5;${COLOR}m${USERNAME}[0m@[1;38;5;${COLOR}m${HOSTNAME}[0m
------------------
[1;38;5;${COLOR}mOS:        [0m${OS}[0m
[1;38;5;${COLOR}mKERNEL:    [0m${KERNEL}[0m
[1;38;5;${COLOR}mUPTIME:    [0m${UPTIME}[0m
[1;38;5;${COLOR}mSHELL:     [0m${SHELL}[0m
[1;38;5;${COLOR}mWM:        [0m${WM}[0m
[1;38;5;${COLOR}mTERMINAL:  [0m${TERMINAL}[0m
")

# Art -------------------------------------------------------------------------

#TODO

ART=$(gum style '    [34m___[0m
   [34m([0m.. [34m|[0m
   [34m([33m<> [34m|[0m
  [34m/ [0m__  [34m\[0m
 [34m( [0m/  \[34m/ |[0m
[33m_[34m/\ [0m__)[34m/[33m_[34m)[0m
[33m\/[34m-____[33m\/[0m
')

# Color -----------------------------------------------------------------------

#TODO

COLOR=$(gum style '[0;30m███[0;31m███[0;32m███[0;33m███[0;34m███[0;35m███[0;36m███[0;37m███[0m
[0;1;90m███[0;1;91m███[0;1;92m███[0;1;93m███[0;1;94m███[0;1;95m███[0;1;96m███[0;1;97m███[0m
')

# Layout ======================================================================

try_print() {
	mono_string=$(printf '%b' "$1" | sed -e 's/\x1B\[[0-9;]*[JKmsu]//g')

	[ "$(printf '%s' "${mono_string}" | wc --lines)" -gt $(( TERM_HEIGHT - PROMPT_HEIGHT )) ] && return 1
	[ "$(printf '%s' "${mono_string}" | wc --max-line-length)" -gt "${TERM_WIDTH}" ] && return 1

	#TODO
	gum style --align center --width="${TERM_WIDTH}" "$1"
	printf '%b' "\033[A"

	exit 0
}

#TODO

# Paper layout
try_print "$(gum join --vertical --align center "${ART}" "${INFO}" "${COLOR}")"

# Classic layout
INFO_COLOR=$(gum join --vertical "${INFO}" "${COLOR}")
try_print "$(gum join --horizontal --align center "${ART}" '  ' "${INFO_COLOR}")"

# Hybrid layout
ART_INFO=$(gum join --horizontal --align center "${ART}" '  ' "${INFO}")
try_print "$(gum join --vertical --align center "${ART_INFO}" "${COLOR}")"

# Other layout
try_print "$(gum join --vertical --align center "${ART}" "${INFO}")"
try_print "$ART_INFO"
try_print "$INFO_COLOR"
try_print "$INFO"

exit 1
