#!/bin/sh

# Prepare ------------------------------------------------------------------------------------------

main_color=4

title="  [38;5;${main_color}m [0m: [1;38;5;${main_color}m${USER}[0m@[1;38;5;${main_color}m$(hostname)[0m"
body=$(gum style --border normal --border-foreground 7 --padding '0 1' --width 30 \
"[38;5;${main_color}m [0m: <your_os>
[38;5;${main_color}m [0m: <your_wm>
[38;5;${main_color}m [0m: $(basename "${SHELL}")
[38;5;${main_color}m [0m: <your_terminal>
[38;5;${main_color}m神[0m: $(uptime -p | cut -c 4- | cut -d ',' -f -2)
[38;5;${main_color}m [0m: <your_packages>")
info=$(gum join --vertical "${title}" "${body}")

art=$(gum style '    [34m___[0m
   [34m([0m.. [34m|[0m
   [34m([33m<> [34m|[0m
  [34m/ [0m__  [34m\[0m
 [34m( [0m/  \[34m/ |[0m
[33m_[34m/\ [0m__)[34m/[33m_[34m)[0m
[33m\/[34m-____[33m\/[0m')

color=$(gum style '[0;30m   [0;31m   [0;32m   [0;33m   [0;34m   [0;35m   [0;36m   [0;37m [0m')


# Display ------------------------------------------------------------------------------------------

terminal_size=$(stty size)
terminal_height=${terminal_size% *}
terminal_width=${terminal_size#* }

prompt_height=${PROMPT_HEIGHT:-1}

print_test() {
	no_color=$(printf '%b' "${1}" | sed -e 's/\x1B\[[0-9;]*[JKmsu]//g')

	[ "$(printf '%s' "${no_color}" | wc --lines)" -gt $(( terminal_height - prompt_height )) ] && return 1
	[ "$(printf '%s' "${no_color}" | wc --max-line-length)" -gt "${terminal_width}" ] && return 1

	gum style --align center --width="${terminal_width}" "${1}" ''
	printf '%b' "\033[A"

	exit 0
}

# Default layout
group_info_color=$(gum join --vertical --align center "${info}" "${color}")
print_test "$(gum join --horizontal --align center '  ' "${art}" '  ' "${group_info_color}")"

# Other layout
print_test "$(gum join --horizontal --align center '  ' "${art}" '  ' "${info}")"
print_test "${group_info_color}"
print_test "${info}"

exit 1