#!/bin/sh

# Prepare ------------------------------------------------------------------------------------------

info=$(gum style --border rounded --border-foreground 6 --padding '1 2' \
"[1;38;5;2mOS        [0m<your_os>
[1;38;5;4mKERNEL    [0m$(uname -sr)
[1;38;5;1mDE        [0m<your_de>
[1;38;5;3mSHELL     [0m$(basename "${SHELL}")
[1;38;5;5mUPTIME    [0m$(uptime -p | cut -c 4-)
[1;38;5;6mPACKAGES  [0m<your_packages>")

art=$(gum style --foreground 6 '    დოოოოოდ
    |     |
    |     |  ╭
    |-Ο Ο-|  │
   Ͼ   ∪   Ͽ │
    |     |  ╯
   ˏ`-.ŏ.-´ˎ
       @
        @')


# Display ------------------------------------------------------------------------------------------

terminal_size=$(stty size)
terminal_height=${terminal_size% *}
terminal_width=${terminal_size#* }

prompt_height=${PROMPT_HEIGHT:-1}

print_test() {
	no_color=$(printf '%b' "${1}" | sed -e 's/\x1B\[[0-9;]*[JKmsu]//g')

	[ "$(printf '%s' "${no_color}" | wc --lines)" -gt $(( terminal_height - prompt_height )) ] && return 1
	[ "$(printf '%s' "${no_color}" | wc --max-line-length)" -gt "${terminal_width}" ] && return 1

	gum style --align center --width="${terminal_width}" "${1}" ''
	printf '%b' "\033[A"

	exit 0
}

# Default layout
print_test "$(gum join --horizontal --align center "${art}" "${info}")"

# Other layout
print_test "${info}"

exit 1