#!/bin/sh

id=1

# Prepare ------------------------------------------------------------------------------------------

info=$(gum style "TODO")

art=$(gum style "$(curl -fsLS "https://gitlab.com/phoneybadger/pokemon-colorscripts/-/raw/main/colorscripts/small/regular/${name}")")

evolution="TODO"


# Display ------------------------------------------------------------------------------------------

terminal_size=$(stty size)
terminal_height=${terminal_size% *}
terminal_width=${terminal_size#* }

prompt_height=${PROMPT_HEIGHT:-1}

print_test() {
	no_color=$(printf '%b' "${1}" | sed -e 's/\x1B\[[0-9;]*[JKmsu]//g')

	[ "$(printf '%s' "${no_color}" | wc --lines)" -gt $(( terminal_height - prompt_height )) ] && return 1
	[ "$(printf '%s' "${no_color}" | wc --max-line-length)" -gt "${terminal_width}" ] && return 1

	gum style --align center --width="${terminal_width}" "${1}" ''
	printf '%b' "\033[A"

	exit 0
}


# Paper layout
print_test "$(gum join --vertical --align center "${art}" '' "${info}" '' "${evolution}")"

# Classic layout
group_info_evolution=$(gum join --vertical "${info}" '' "${evolution}")
print_test "$(gum join --horizontal --align center "${art}" '  ' "${group_info_evolution}")"

# Hybrid layout
group_art_info=$(gum join --horizontal --align center "${art}" '  ' "${info}")
print_test "$(gum join --vertical --align center "${group_art_info}" '' "${evolution}")"

# Other layout
print_test "$(gum join --vertical --align center "${art}" '' "${info}")"
print_test "${group_art_info}"
print_test "${group_info_evolution}"
print_test "${info}"

exit 1